# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Run cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run start-e2e-test-site
      - name: Store Cypress videos
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: |
            cypress/videos/
      - run: npm run lint
      - run: ./node_modules/.bin/prettier --check .
